### ISSUE TITLE
A quick question about the model config files

### ISSUE THREAD

**Issue by azshue** [Vladimir2506/Pointformer#8]
Hello authors, 

I really appreciate this work, and thanks for your efforts in releasing the code.

I wonder if you could help me understand one of the model setups in your config file. 

From [this line](https://github.com/Vladimir2506/Pointformer/blob/main/configs/pointformer/votenet_ptr_scannet-3d-18class.py#L20), it appears that the Local-Global Transformer (i.e., decoder) is not used in your models for indoor object detection. 
Could you please confirm if this is the correct setting?

Thank you!

**Comment by Vladimir2506** [comment]
@azshue Thank you for your interest in our work. From the further experiment results, the decoder module contributes little to performance on the indoor datasets, thus we omit this in the indoor experiments and leave it to the outdoors.

**Comment by azshue** [comment]
Thank you for the reply! This answers my question.
